# Generated by Django 3.1.3 on 2020-11-09 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название товара')),
                ('articul', models.CharField(max_length=255, unique=True, verbose_name='Артикул товара')),
                ('price_zakup', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Закупочная цена')),
                ('price_rozn', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Розничная цена')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО пользователя')),
                ('address', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Адрес доставки')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email клиента')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('role', models.CharField(choices=[('CL', 'client'), ('MGR', 'manager')], default='CL', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Розничная цена товара на момент заказа')),
                ('count', models.IntegerField(verbose_name='Количество товара')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='main.cart', verbose_name='Корзина')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item', verbose_name='Товар')),
            ],
            options={
                'unique_together': {('item', 'cart')},
            },
        ),
    ]
